<?php
require_once get_stylesheet_directory().'/inc/daily-web-broadcast.php';
get_header();
while(have_posts()):the_post();
$slug=get_post_field('post_name',get_the_ID());
$catalog=r9_product_catalog();
$item=$catalog[$slug]??array(get_the_title(),'Region 9 Weather information and decision support.');
?>
<?php if($slug!=='daily'):?>
<header class="r9-page-header"><div class="r9-wrap r9-page-header-inner"><div><span class="r9-eyebrow">REGION 9 WEATHER STUDIO</span><h1><?php the_title();?></h1><p><?php echo esc_html($item[1]);?></p></div><span class="r9-risk r9-page-risk <?php echo esc_attr(r9_risk_class());?>"><?php echo esc_html(r9_risk_label());?> risk</span></div></header>
<?php endif;?>
<main class="r9-wrap r9-page-grid"><article class="r9-page-content">
<?php if($slug==='daily'):?><?php echo function_exists('r9_daily_web_renderer')?r9_daily_web_renderer():(function_exists('r9ls_theme_daily_carousel')?r9ls_theme_daily_carousel():r9ls_theme_product_grid('daily'));?>
<?php elseif($slug==='about'):?><section class="r9-about-layout"><div class="r9-panel r9-portrait-card"><div class="r9-panel-head"><h2>Portrait</h2></div><div class="r9-portrait-placeholder"><span aria-hidden="true">＋</span><strong>Portrait Placeholder</strong><small>Upload a professional portrait through the WordPress page editor or Media Library.</small></div></div><div class="r9-panel r9-bio-card"><div class="r9-panel-head"><h2>Biography</h2></div><div class="r9-discussion"><?php $content=trim(get_the_content()); echo $content?apply_filters('the_content',$content):'<p>Add a professional biography, Region 9 Weather background, service area, forecasting experience, and public-service mission here.</p>';?></div></div></section>
<?php elseif($slug==='severe-weather'):?>
<section class="r9-severe-hub">
  <a class="r9-severe-hub-card r9-severe-hub-alerts" href="<?php echo esc_url(home_url('/alerts/'));?>"><span>LIVE</span><h2>Alert Center</h2><p>View active Region 9 and nearby alerts, localized impacts, safety actions, radar, and official bulletins.</p><strong>Open Alert Center →</strong></a>
  <a class="r9-severe-hub-card" href="<?php echo esc_url(home_url('/storm-timing/'));?>"><h2>Storm Timing</h2><p>Arrival, peak-impact, and exit windows for Region 9 communities.</p></a>
  <a class="r9-severe-hub-card" href="<?php echo esc_url(home_url('/threat-breakdown/'));?>"><h2>Threat Breakdown</h2><p>Damaging wind, hail, tornado, flooding, and lightning risk.</p></a>
  <a class="r9-severe-hub-card" href="<?php echo esc_url(home_url('/watches-warnings/'));?>"><h2>Watches &amp; Warnings</h2><p>Plain-language explanations and recommended actions.</p></a>
</section>
<section class="r9-content-pair"><div class="r9-panel"><div class="r9-panel-head"><h2>Severe Weather Media</h2></div><?php echo r9_media_placeholder('Severe Weather Graphic or Photo');?></div><div class="r9-panel"><div class="r9-panel-head"><h2>Forecast Discussion</h2></div><div class="r9-discussion"><?php $content=trim(get_the_content()); echo $content?apply_filters('the_content',$content):'<p>Add the latest severe-weather discussion in the WordPress page editor.</p>';?></div></div></section>
<?php elseif($slug==='city-forecast'):?><section class="r9-city-forecast-shell"><div id="r9-city-forecast" class="r9-city-forecast" data-city="<?php echo esc_attr(isset($_GET['city'])?sanitize_text_field(wp_unslash($_GET['city'])):'Kankakee');?>"><section class="r9-panel"><h2>Loading full forecast…</h2><p>Connecting to the official National Weather Service forecast.</p></section></div></section>
<?php elseif($slug==='radar'):?><section class="r9-panel r9-radar"><iframe title="KILX WeatherFront Radar" loading="lazy" allowfullscreen src="<?php echo esc_url(r9_setting('radar_url','https://app.weatherfront.com/radar/KILX'));?>"></iframe></section>
<?php elseif($slug==='alerts'): if(isset($_GET['alert'])&&$_GET['alert']!==''):?><div id="r9-alert-detail" class="r9-alert-detail" data-alert-url="<?php echo esc_attr(esc_url_raw(wp_unslash($_GET['alert'])));?>"><section class="r9-panel r9-alert-detail-loading"><h2>Loading official alert…</h2><p>Region 9 Weather is retrieving the latest bulletin.</p></section></div><?php else: echo do_shortcode('[region9_alert_center]'); endif;
else: ?><?php $operational=function_exists('r9_render_operational_page')?r9_render_operational_page($slug):''; if($operational){ echo $operational; } else { $grid = r9ls_theme_product_grid($slug); if($grid){ echo $grid; } else { ?><section class="r9-operational-layout r9-forecast-standard"><div class="r9-panel r9-operational-main"><div class="r9-panel-head"><span class="r9-eyebrow">REGION 9 FORECAST</span><h2><?php echo esc_html($item[0]);?> Media</h2></div><?php echo r9_media_placeholder($item[0].' Graphic or Photo');?><div class="r9-status-row"><span class="r9-status-pill">Updated <?php echo esc_html(r9_updated_label());?></span><span class="r9-status-pill <?php echo esc_attr(r9_risk_class());?>"><?php echo esc_html(r9_risk_label());?> risk</span><span class="r9-status-pill">Confidence monitored</span></div></div><div class="r9-panel"><div class="r9-panel-head"><h2>Forecast Discussion</h2></div><div class="r9-discussion"><?php $content=trim(get_the_content()); echo $content?apply_filters('the_content',$content):'<p>The latest meteorologist discussion for this product will appear here after the next forecast update. Region 9 Weather will continue to show verified public information without exposing draft notes.</p>';?></div><div class="r9-key-info"><h3>Key Information</h3><ul><li>Risk: <?php echo esc_html(r9_risk_label());?></li><li>Counties: Region 9 coverage area</li><li>Timing: Updated with approved forecast products</li></ul></div></div></section><?php } } endif; ?>
</article><aside><?php if(is_active_sidebar('r9-forecast-sidebar'))dynamic_sidebar('r9-forecast-sidebar');elseif(function_exists('r9_default_sidebar'))echo r9_default_sidebar();else echo '<section class="r9-panel"><div class="r9-panel-head"><h3>Region 9 Coverage</h3></div><div class="r9-discussion"><p>Kankakee, Iroquois, Ford, Livingston, Champaign, Vermilion, McLean, DeWitt, and Piatt counties.</p></div></section>';?></aside></main>
<?php endwhile; get_footer();
