<?php if(!defined('ABSPATH'))exit;
add_action('admin_menu',function(){
 if(function_exists('r9ls_theme_rc1_active') && r9ls_theme_rc1_active()){
  remove_menu_page('r9-studio');
  remove_submenu_page('r9-studio','r9-studio-setup');
  remove_submenu_page('r9-studio','r9-studio-health');
  remove_submenu_page('r9-studio','r9-studio-backup');
  // The active plugin owns every Region 9 Studio submenu and callback.
  return;
 }
 add_menu_page('Region 9 Studio','Region 9 Studio','manage_options','r9-studio','r9_studio_admin','dashicons-cloud','3');
 add_submenu_page('r9-studio','Site Setup','Site Setup','manage_options','r9-studio-setup','r9_studio_setup_page');
 add_submenu_page('r9-studio','System Health','System Health','manage_options','r9-studio-health','r9_studio_health_page');
 add_submenu_page('r9-studio','Backup & Restore','Backup & Restore','manage_options','r9-studio-backup','r9_studio_backup_page');
 add_submenu_page('r9-studio','Live Controls','Live Controls','manage_options','customize.php?autofocus[section]=r9_studio');
 foreach(r9_restored_admin_pages() as $slug=>$label){ add_submenu_page('r9-studio',$label,$label,'manage_options',$slug,'r9_restored_admin_page'); }
},99);

function r9_restored_admin_pages(){return array('r9-studio-partners'=>'Partners','r9-studio-clients'=>'Clients','r9-studio-production'=>'Production','r9-studio-rural-reports'=>'Rural Reports','r9-studio-rural-operations'=>'Rural Operations','r9-studio-protection'=>'Protection');}
function r9_restored_admin_page(){if(!current_user_can('manage_options'))return;$slug=sanitize_key($_GET['page']??'');$pages=r9_restored_admin_pages();$title=$pages[$slug]??'Region 9 Operations';?><div class="wrap"><h1><?php echo esc_html($title);?></h1><p>This fallback entry point preserves the Region 9 Weather administrative inventory when Live Studio is inactive.</p><p>No production data is fabricated here. Activate Region 9 Live Studio 17.1.0 for the authoritative operational dashboard.</p></div><?php }
add_action('admin_post_r9_build_site','r9_build_site');
add_action('admin_post_r9_export_settings','r9_export_settings');
add_action('admin_post_r9_import_settings','r9_import_settings');
function r9_studio_admin(){ if(!current_user_can('manage_options'))return; if(function_exists('r9ls_theme_rc1_active')&&r9ls_theme_rc1_active()){ wp_safe_redirect(admin_url('admin.php?page=r9ls')); exit; } ?>
<div class="wrap"><h1>Region 9 Weather Studio 17.1.0</h1><p>Legacy theme controls are shown only when Region 9 Live Studio is inactive. The supported plugin experience includes Emergency Mode, system health monitoring, observation-age warnings, accessibility controls, social sharing, live alerts, clickable city forecasts, and settings backup/restore.</p>
<div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(280px,1fr));gap:16px;max-width:1200px">
<?php foreach(array(
 'Live Studio Controls'=>array('Risk, Latest Weather Update, Emergency Mode, live video, impacts, graphics, social links, and accessibility.','customize.php?autofocus[section]=r9_studio','button-primary'),
 'Build / Repair Site'=>array('Create or repair the page structure and navigation.','admin.php?page=r9-studio-setup',''),
 'System Health'=>array('Check NWS alerts, forecasts, observations, radar, WordPress, PHP, and theme status.','admin.php?page=r9-studio-health',''),
 'Backup & Restore'=>array('Export or import Region 9 Studio settings as JSON.','admin.php?page=r9-studio-backup',''),
 'Menus'=>array('Manage primary and dropdown navigation.','nav-menus.php',''),
 'Widgets'=>array('Manage operational, alert, forecast, and footer widget areas.','widgets.php',''),'Partners'=>array('Open preserved Partners administration entry point.','admin.php?page=r9-studio-partners',''),'Clients'=>array('Open preserved Clients administration entry point.','admin.php?page=r9-studio-clients',''),'Production'=>array('Open preserved Production administration entry point.','admin.php?page=r9-studio-production',''),'Rural Operations'=>array('Open preserved Rural Operations entry point.','admin.php?page=r9-studio-rural-operations','')
 ) as $title=>$x): ?><div class="card"><h2><?php echo esc_html($title);?></h2><p><?php echo esc_html($x[0]);?></p><p><a class="button <?php echo esc_attr($x[2]);?>" href="<?php echo esc_url(admin_url($x[1]));?>">Open</a></p></div><?php endforeach;?>
</div></div><?php }
function r9_studio_health_page(){if(!current_user_can('manage_options'))return;$status=r9_status_endpoint()->get_data();?><div class="wrap"><h1>Region 9 System Health</h1><p>Last checked: <?php echo esc_html(wp_date('M j, Y g:i A T'));?></p><table class="widefat striped"><thead><tr><th>Service</th><th>Status</th><th>HTTP</th><th>Latency</th></tr></thead><tbody><?php foreach($status['services'] as $name=>$x):?><tr><td><?php echo esc_html(ucwords($name));?></td><td><strong style="color:<?php echo $x['ok']?'#087f3d':'#b42318';?>"><?php echo $x['ok']?'Online':'Unavailable';?></strong></td><td><?php echo esc_html((string)$x['code']);?></td><td><?php echo $x['latency']!==null?esc_html($x['latency'].' ms'):'—';?></td></tr><?php endforeach;?></tbody></table><h2>Platform</h2><ul><li>WordPress <?php echo esc_html(get_bloginfo('version'));?></li><li>PHP <?php echo esc_html(PHP_VERSION);?></li><li>Theme <?php echo esc_html(R9_STUDIO_VERSION);?></li><li>SSL <?php echo is_ssl()?'Active':'Not detected';?></li></ul></div><?php }
function r9_studio_backup_page(){if(!current_user_can('manage_options'))return;?><div class="wrap"><h1>Backup & Restore</h1><?php if(isset($_GET['imported']))echo '<div class="notice notice-success"><p>Region 9 settings imported.</p></div>';?><h2>Export</h2><p>Download all Region 9 Studio theme settings as JSON.</p><p><a class="button button-primary" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=r9_export_settings'),'r9_export_settings'));?>">Download Settings Backup</a></p><hr><h2>Import</h2><form method="post" enctype="multipart/form-data" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('r9_import_settings');?><input type="hidden" name="action" value="r9_import_settings"><input type="file" name="r9_settings" accept="application/json,.json" required><p><button class="button">Import Settings</button></p></form></div><?php }
function r9_export_settings(){if(!current_user_can('manage_options')||!wp_verify_nonce($_GET['_wpnonce']??'','r9_export_settings'))wp_die('Not authorized.');$mods=get_theme_mods();header('Content-Type: application/json');header('Content-Disposition: attachment; filename="region9-studio-settings-'.gmdate('Ymd-His').'.json"');echo wp_json_encode(array('version'=>R9_STUDIO_VERSION,'exported'=>current_time('c'),'theme_mods'=>$mods),JSON_PRETTY_PRINT);exit;}
function r9_import_settings(){if(!current_user_can('manage_options')||!check_admin_referer('r9_import_settings'))wp_die('Not authorized.');if(empty($_FILES['r9_settings']['tmp_name']))wp_die('No file uploaded.');$data=json_decode(file_get_contents($_FILES['r9_settings']['tmp_name']),true);if(!is_array($data)||empty($data['theme_mods'])||!is_array($data['theme_mods']))wp_die('Invalid backup file.');foreach($data['theme_mods'] as $k=>$v)set_theme_mod(sanitize_key($k),$v);wp_safe_redirect(admin_url('admin.php?page=r9-studio-backup&imported=1'));exit;}
function r9_studio_setup_page(){ if(!current_user_can('manage_options'))return; ?><div class="wrap"><h1>Region 9 Studio Site Setup</h1><?php if(isset($_GET['built'])) echo '<div class="notice notice-success"><p>The Region 9 site structure and menu were created or repaired.</p></div>';?><p>This safe setup routine creates missing pages, assigns the homepage, and creates the Region 9 Studio navigation. Existing pages are not deleted.</p><form method="post" action="<?php echo esc_url(admin_url('admin-post.php'));?>"><?php wp_nonce_field('r9_build_site');?><input type="hidden" name="action" value="r9_build_site"><p><button class="button button-primary button-hero">Build or Repair Entire Site</button></p></form></div><?php }
function r9_build_site(){
 if(!current_user_can('manage_options')||!check_admin_referer('r9_build_site')) wp_die('Not authorized.');
 $ids=array(); foreach(r9_studio_pages() as $slug=>$title){$page=get_page_by_path($slug); if(!$page){$content=''; if($slug==='alerts')$content='[region9_alert_center]'; elseif($slug==='radar')$content='<div class="r9-radar"><iframe title="KILX WeatherFront Radar" loading="lazy" allowfullscreen src="'.esc_url(r9_setting('radar_url','https://app.weatherfront.com/radar/KILX')).'"></iframe></div>'; elseif($slug==='storm-timing')$content='<p>Add current arrival, peak-impact, and exit windows for Region 9 communities.</p>'; elseif($slug==='threat-breakdown')$content='<p>Add the latest damaging wind, hail, tornado, flooding, and lightning threat assessment.</p>'; elseif($slug==='watches-warnings')$content='<p>Explain active watches, warnings, included counties, expiration times, and recommended actions in plain language.</p>'; elseif($slug==='outage-tracker')$content='[region9_outage_tracker]'; elseif(in_array($slug,array('partners','clients','production','rural-operations','rural-reports','protection','backup'),true))$content='<p>This Region 9 Weather page is preserved for 17.1 parity. Add only approved operational content.</p>';  $id=wp_insert_post(array('post_title'=>$title,'post_name'=>$slug,'post_status'=>'publish','post_type'=>'page','post_content'=>$content));}else{$id=$page->ID;} $ids[$slug]=(int)$id;}
 $home=get_page_by_path('home'); if(!$home){$home_id=wp_insert_post(array('post_title'=>'Home','post_name'=>'home','post_status'=>'publish','post_type'=>'page','post_content'=>'[region9_studio_home]'));}else{$home_id=$home->ID;if(strpos($home->post_content,'[region9_studio_home]')===false)wp_update_post(array('ID'=>$home_id,'post_content'=>'[region9_studio_home]'));}
 update_option('show_on_front','page'); update_option('page_on_front',$home_id);
 $menu_name='Region 9 Studio Menu'; $menu=wp_get_nav_menu_object($menu_name); $menu_id=$menu?$menu->term_id:wp_create_nav_menu($menu_name);
 if($menu_id&&!is_wp_error($menu_id)){$existing=wp_get_nav_menu_items($menu_id);if($existing){foreach($existing as $item)wp_delete_post($item->ID,true);}wp_update_nav_menu_item($menu_id,0,array('menu-item-title'=>'Home','menu-item-object'=>'page','menu-item-object-id'=>$home_id,'menu-item-type'=>'post_type','menu-item-status'=>'publish'));$order=array('about','severe-weather','hazards','temperature-outlook','precipitation-outlook','travel-outdoor','agriculture','anxiety','outage-tracker','partners','clients','radar');$parent_ids=array();foreach($order as $slug){$mid=wp_update_nav_menu_item($menu_id,0,array('menu-item-title'=>r9_studio_pages()[$slug],'menu-item-object'=>'page','menu-item-object-id'=>$ids[$slug],'menu-item-type'=>'post_type','menu-item-status'=>'publish'));$parent_ids[$slug]=(int)$mid;}if(!empty($parent_ids['severe-weather'])){foreach(array('alerts'=>'Alert Center','storm-timing'=>'Storm Timing','threat-breakdown'=>'Threat Breakdown','watches-warnings'=>'Watches & Warnings') as $slug=>$label)wp_update_nav_menu_item($menu_id,0,array('menu-item-title'=>$label,'menu-item-object'=>'page','menu-item-object-id'=>$ids[$slug],'menu-item-type'=>'post_type','menu-item-status'=>'publish','menu-item-parent-id'=>$parent_ids['severe-weather']));}$loc=get_theme_mod('nav_menu_locations',array());$loc['r9_studio_menu']=$menu_id;set_theme_mod('nav_menu_locations',$loc);}
 flush_rewrite_rules();wp_safe_redirect(admin_url('admin.php?page=r9-studio-setup&built=1'));exit;
}
