<?php
if (!defined('ABSPATH')) { define('ABSPATH', __DIR__); }
error_reporting(E_ALL);
set_error_handler(function($severity, $message, $file, $line){ throw new ErrorException($message, 0, $severity, $file, $line); });
function absint($v){ return abs((int)$v); } function sanitize_key($v){ return preg_replace('/[^a-z0-9_\-]/','', strtolower((string)$v)); }
function sanitize_text_field($v){ return is_array($v) ? '' : trim(strip_tags((string)$v)); } function sanitize_email($v){ return filter_var((string)$v, FILTER_SANITIZE_EMAIL); } function esc_url_raw($v){ return filter_var((string)$v, FILTER_SANITIZE_URL); } function wp_json_encode($v,$o=0){ return json_encode($v,$o); }
$GLOBALS['filters']=array(); function apply_filters($tag,$value){ foreach (($GLOBALS['filters'][$tag] ?? array()) as $cb) { $value = $cb($value); } return $value; } function add_filter($tag,$cb){ $GLOBALS['filters'][$tag][]=$cb; } function add_action(){} function add_shortcode(){} function register_rest_route($ns,$route,$args){ $GLOBALS['rest_routes'][$ns.$route]=$args; }
function __return_true(){ return true; } function current_time($type='mysql'){ return $type==='timestamp' ? time() : date('Y-m-d H:i:s'); } function wp_date($f,$ts=null){ return date($f,$ts?:time()); } function get_bloginfo($k){ return '6.6-test'; }
$GLOBALS['wp_options']=array(); $GLOBALS['wp_transients']=array(); $GLOBALS['scheduled']=array(); $GLOBALS['http_queue']=array(); $GLOBALS['db_writes']=0;
function get_option($k,$d=false){ return $GLOBALS['wp_options'][$k] ?? $d; } function update_option($k,$v,$a=false){ $GLOBALS['db_writes']++; $GLOBALS['wp_options'][$k]=$v; return true; } function delete_transient($k){ unset($GLOBALS['wp_transients'][$k]); }
function set_transient($k,$v,$ttl){ $GLOBALS['wp_transients'][$k]=array($v,time()+$ttl); } function get_transient($k){ if(!isset($GLOBALS['wp_transients'][$k])) return false; if($GLOBALS['wp_transients'][$k][1] < time()){ unset($GLOBALS['wp_transients'][$k]); return false;} return $GLOBALS['wp_transients'][$k][0]; }
function wp_next_scheduled($h){ return $GLOBALS['scheduled'][$h] ?? false; } function wp_schedule_event($t,$r,$h){ if(isset($GLOBALS['scheduled'][$h])) return false; $GLOBALS['scheduled'][$h]=$t; return true; } function wp_clear_scheduled_hook($h){ unset($GLOBALS['scheduled'][$h]); } function wp_parse_args($a,$d){ return array_merge($d,(array)$a); }
function wp_remote_get($url,$args=array()){ return array_shift($GLOBALS['http_queue']) ?: array('response'=>array('code'=>503),'body'=>''); } function wp_remote_retrieve_response_code($r){ return $r['response']['code'] ?? 0; } function wp_remote_retrieve_body($r){ return $r['body'] ?? ''; } class WP_Error { public $code; public $message; public $data; public function __construct($c,$m,$d=array()){ $this->code=$c; $this->message=$m; $this->data=$d; } } function is_wp_error($v){ return $v instanceof WP_Error; }
function shortcode_atts($pairs,$atts){ return array_merge($pairs,(array)$atts); } function esc_attr($v){ return htmlspecialchars((string)$v,ENT_QUOTES); } function esc_html($v){ return htmlspecialchars((string)$v,ENT_QUOTES); } function esc_url($v){ return esc_attr($v); } function esc_html__($v){ return esc_html($v); } function sanitize_html_class($v){ return sanitize_key($v); } function wp_kses_post($v){ return (string)$v; } function wpautop($v){ return '<p>'.esc_html($v).'</p>'; } function r9_media_placeholder($label){ return '<div class="r9-image" role="img" aria-label="'.esc_attr($label).'"></div>'; }
define('MINUTE_IN_SECONDS',60); define('HOUR_IN_SECONDS',3600); define('R9LS_DIR', dirname(__DIR__) . '/plugins/region9-live-studio/');
require R9LS_DIR.'includes/class-audit-log.php'; require R9LS_DIR.'includes/class-gis-engine.php'; require R9LS_DIR.'includes/class-rule-engine.php'; require R9LS_DIR.'includes/class-national-guidance.php'; require R9LS_DIR.'includes/class-material-change-engine.php'; require R9LS_DIR.'includes/class-scheduler.php'; require R9LS_DIR.'includes/class-timing-engine.php'; require R9LS_DIR.'includes/class-product-generator.php'; require R9LS_DIR.'includes/class-rest-api.php';
require dirname(__DIR__).'/inc/live-studio-integration.php';
$passes=0; function ok($name,$condition){ global $passes; if(!$condition){ fwrite(STDERR,"FAIL: $name\n"); exit(1);} $passes++; echo "PASS: $name\n"; }
function poly($x1,$y1,$x2,$y2){ return array('type'=>'Polygon','coordinates'=>array(array(array($x1,$y1),array($x2,$y1),array($x2,$y2),array($x1,$y2),array($x1,$y1)))); }
function fixture_sources($scenario){ $base=array('spc_day1'=>array('status'=>'healthy','hazards'=>array()),'wpc_day1_ero'=>array('status'=>'healthy','hazards'=>array()),'wpc_day1_qpf'=>array('status'=>'healthy','county_precipitation'=>array()),'nws_alerts'=>array('status'=>'healthy','hazards'=>array())); $ch=poly(-88.4,39.9,-88.0,40.3); $ka=poly(-88.2,41.0,-87.6,41.25); switch($scenario){case 'severe': $base['spc_day1']['hazards'][]=array('risk'=>4,'geometry'=>$ch); break; case 'warning': $base['nws_alerts']['hazards'][]=array('risk'=>3,'geometry'=>$ch); break; case 'warning_upgrade': $base['nws_alerts']['hazards'][]=array('risk'=>5,'geometry'=>$ch); break; case 'warning_extension': $base['nws_alerts']['hazards'][]=array('risk'=>3,'geometry'=>$ka); break; case 'warning_cancel': break; case 'flooding': $base['wpc_day1_ero']['hazards'][]=array('risk'=>4,'geometry'=>$ch); break; case 'heat': $base['nws_alerts']['hazards'][]=array('risk'=>2,'geometry'=>$ch,'event'=>'Heat Advisory'); break; case 'winter_placeholder': $base['nws_alerts']['hazards'][]=array('risk'=>1,'geometry'=>$ch,'event'=>'Winter Weather Advisory'); break; case 'one_unavailable': $base['spc_day1']=array('status'=>'unavailable'); break; case 'multi_unavailable': $base['spc_day1']=array('status'=>'unavailable'); $base['wpc_day1_qpf']=array('status'=>'unavailable'); break; case 'stale': $base['spc_day1']=array('status'=>'stale','hazards'=>array(array('risk'=>2,'geometry'=>$ch))); break; case 'malformed': $base['spc_day1']=array('status'=>'malformed_geometry'); break; case 'zero_hazard': break;} return $base; }
$a=new R9LS_Audit_Log(); $g=new R9LS_GIS_Engine(R9LS_DIR.'data/region9-counties.geojson'); $r=new R9LS_Rule_Engine($g,$a); $m=new R9LS_Material_Change_Engine($a); $ng=new R9LS_National_Guidance($g,$a,array('cache_ttl'=>1,'stale_ttl'=>60)); $s=new R9LS_Scheduler($a,$r,$m,$ng); $pg=new R9LS_Product_Generator($r,$m,$a,new R9LS_Timing_Engine());
$geo=json_decode(file_get_contents(R9LS_DIR.'data/region9-counties.geojson'),true); $expected=array('17091'=>'Kankakee','17075'=>'Iroquois','17053'=>'Ford','17105'=>'Livingston','17039'=>'DeWitt','17147'=>'Piatt','17019'=>'Champaign','17183'=>'Vermilion','17113'=>'McLean'); $seen=array();
foreach($geo['features'] as $f){ $name=$f['properties']['name']; $geoid=$f['properties']['GEOID']; $seen[$geoid]=$name; ok("geometry type $name", in_array($f['geometry']['type'],array('Polygon','MultiPolygon'),true)); $rings=$f['geometry']['type']==='Polygon'?$f['geometry']['coordinates']:array_merge(...array_map(fn($p)=>$p,$f['geometry']['coordinates'])); foreach($rings as $ring){ ok("ring closure $name", $ring[0]===$ring[count($ring)-1]); ok("more than rectangle vertices $name", count($ring)>5); $unique=array_unique(array_map(fn($p)=>implode(',',$p),$ring)); ok("not bounding rectangle $name", count($unique)>4); $area=0; for($i=0;$i<count($ring)-1;$i++){ $area += $ring[$i][0]*$ring[$i+1][1]-$ring[$i+1][0]*$ring[$i][1]; } ok("non-empty area $name", abs($area/2)>0.01); } }
ok('exact Region 9 county GEOIDs', $seen===$expected);
ok('GIS severe intersection still passes', in_array('Champaign',$g->intersect_source(array('status'=>'healthy','hazards'=>array(array('risk'=>3,'geometry'=>poly(-88.4,39.9,-88.0,40.3)))))['affected_counties'],true));
$s->activate(); ok('fresh activation schedules event', wp_next_scheduled(R9LS_Scheduler::HOOK)!==false); $settings=get_option(R9LS_Scheduler::SETTINGS,array()); update_option(R9LS_Product_Generator::STATE,array('publication_version'=>'pub-alpha8','approval_state'=>'approved','publication_state'=>'published','decision_output'=>array(),'history_id'=>'hist-alpha8','rollback_reference'=>'none'),false); update_option(R9LS_Product_Generator::HISTORY,array(array('history_id'=>'hist-alpha8')),false); update_option('r9ls_editor_overrides',array('override1'=>array('expires'=>'2999-01-01T00:00')),false); $s->deactivate(); ok('deactivation clears event', wp_next_scheduled(R9LS_Scheduler::HOOK)===false); $s->activate(); ok('reactivation schedules one event', wp_next_scheduled(R9LS_Scheduler::HOOK)!==false); ok('upgrade preserves settings', get_option(R9LS_Scheduler::SETTINGS,array())['automatic_publishing']===0); ok('upgrade preserves canonical state', get_option(R9LS_Product_Generator::STATE,array())['publication_version']==='pub-alpha8'); ok('upgrade preserves history', count(get_option(R9LS_Product_Generator::HISTORY,array()))===1); ok('upgrade preserves active overrides', isset(get_option('r9ls_editor_overrides',array())['override1'])); ok('plugin inactive theme fallback', r9ls_theme_fallback_language()!=='');
$prev=$r->evaluate_all(fixture_sources('quiet')); update_option(R9LS_Scheduler::CACHE,$prev,false); foreach(array('quiet','severe','warning','warning_upgrade','warning_extension','warning_cancel','flooding','heat','winter_placeholder','one_unavailable','multi_unavailable','stale','malformed','zero_hazard') as $scenario){ $cur=$r->evaluate_all(fixture_sources($scenario)); $changes=$m->detect($prev,$cur); ok("scenario $scenario county scores", isset($cur['Travel']['county_scores']) && count($cur['Travel']['county_scores'])===9); ok("scenario $scenario Region 9 score", isset($cur['Travel']['score'])); ok("scenario $scenario confidence", isset($cur['Travel']['confidence']) && $cur['Travel']['confidence']>=0); ok("scenario $scenario pending approval private", $m->publish('missing-'.$scenario)===false); update_option(R9LS_Scheduler::CACHE,$cur,false); update_option(R9LS_Product_Generator::STATE,array('publication_version'=>'pub-'.$scenario,'approval_state'=>'approved','publication_state'=>'published','decision_output'=>$cur,'history_id'=>'hist-'.$scenario,'rollback_reference'=>'rb'),false); $products=$pg->generate_from_approved_state('rc1',$scenario); ok("scenario $scenario public rendering", isset($products['travel']['summary'])); ok("scenario $scenario rollback", $m->rollback('hist-'.$scenario)===true); }
$GLOBALS['wp_options'][R9LS_Scheduler::SETTINGS]['active_interval_minutes']=15; ok('15-minute active weather scheduling supported', $s->active_interval_minutes()===15); ok('duplicate event prevention', $s->schedule_event()===false); set_transient(R9LS_Scheduler::LOCK,time(),60); ok('overlapping run lock', $s->validate('scheduled')['status']==='locked'); set_transient(R9LS_Scheduler::LOCK,time()-2000,60); ok('stale lock expiry', $s->locked()===false); ok('next run calculation', is_int($s->next_validation())); ok('no automatic publishing by default', get_option(R9LS_Scheduler::SETTINGS,array())['automatic_publishing']===0);
$before=get_option(R9LS_Product_Generator::STATE,array()); ok('approval required', $m->publish('not-approved')===false); $changes=$m->detect($prev,$r->evaluate_all(fixture_sources('severe'))); if($changes){ $id=$changes[0]['id']; $m->decide($id,'rejected','rc1'); ok('rejected changes auditable', count($m->history())>0); } update_option('r9ls_editor_overrides',array('old'=>array('expires'=>'2000-01-01T00:00'))); ok('expired overrides disappear', $m->expire_overrides()===array()); ok('auto-publish fails closed degraded source', fixture_sources('one_unavailable')['spc_day1']['status']!=='healthy'); ok('auto-publish fails closed low confidence', $r->evaluate_all(fixture_sources('multi_unavailable'))['Travel']['confidence']<100);
$http=count($GLOBALS['http_queue']); $writes=$GLOBALS['db_writes']; r9ls_theme_card('travel'); ok('no external weather HTTP during rendering', count($GLOBALS['http_queue'])===$http); ok('no public database writes during rendering', $GLOBALS['db_writes']===$writes); ok('stale approved state labeled', r9ls_theme_status(array('updated_at'=>'2000-01-01 00:00:00'))['state']==='stale'); ok('current conditions/radar/alerts placeholders remain available', function_exists('r9ls_theme_product_grid')); ok('no MutationObserver introduced', strpos(file_get_contents(dirname(__DIR__).'/assets/js/studio.js'),'MutationObserver')===false && strpos(file_get_contents(dirname(__DIR__).'/assets/js/v52.js'),'MutationObserver')===false);
$admin=file_get_contents(R9LS_DIR.'includes/class-admin.php'); $rest=file_get_contents(R9LS_DIR.'includes/class-rest-api.php'); ok('admin-post nonce review', strpos($admin,'check_admin_referer')!==false); ok('capability checks review', strpos($admin,'current_user_can')!==false); ok('REST public filtering assertion', strpos($rest,'rule_trace')!==false); ok('public write-route absence', strpos($rest,"'methods'=>'POST'")===false && strpos($rest,'WP_REST_Server::CREATABLE')===false); ok('no obvious secret leakage', !preg_match('/(api[_-]?key|secret|token)\s*=/i',$admin.$rest));
$start=microtime(true); $mem0=memory_get_usage(true); $rest=new R9LS_REST_API($pg); $rest->read('all'); $dur=round((microtime(true)-$start)*1000,3); $peak=memory_get_peak_usage(true)-$mem0; ok('public REST benchmark under 100ms in harness', $dur<100); ok('validation memory benchmark recorded', $peak>=0); $build_dir = dirname(__DIR__).'/build'; if (!is_dir($build_dir)) { mkdir($build_dir,0777,true); } file_put_contents(dirname(__DIR__).'/build/rc1-test-report.json', json_encode(array('passes'=>$passes,'rest_ms'=>$dur,'peak_memory_delta'=>$peak,'php'=>PHP_VERSION,'generated_at'=>date('c')), JSON_PRETTY_PRINT));
echo "Region 9 17.1 validation suite complete with $passes assertions.\n";
