<?php
$root=dirname(__DIR__);$mode='full';foreach($argv as $arg){if(in_array($arg,array('--quick','--full','--stress'),true))$mode=substr($arg,2);}
$results=array();$failures=0;$warnings=0;$assertions=0;$started=microtime(true);$build=$root.'/build';if(!is_dir($build))mkdir($build,0777,true);
function v171_result($category,$name,$status,$detail=''){global $results,$failures,$warnings,$assertions;$results[]=compact('category','name','status','detail');$assertions++;if($status==='FAIL')$failures++;if(in_array($status,array('WARNING','UPSTREAM UNAVAILABLE'),true))$warnings++;echo "[$status] [$category] $name".($detail!==''?' — '.$detail:'')."\n";}
function v171_check($category,$name,$condition,$detail=''){v171_result($category,$name,$condition?'PASS':'FAIL',$detail);}
function v171_read($relative){global $root;$path=$root.'/'.$relative;if(!is_file($path)){v171_result('INTEGRITY','Required file '.$relative,'FAIL','missing');return '';}return file_get_contents($path);}
function v171_run($category,$command,$critical=true){global $root,$assertions;$lines=array();$code=0;$before=microtime(true);exec('cd '.escapeshellarg($root).' && '.$command.' 2>&1',$lines,$code);$detail='exit='.$code.', '.number_format(microtime(true)-$before,3).'s';$pass_count=0;foreach($lines as $line){if(strpos($line,'PASS:')===0)$pass_count++;}$assertions+=$pass_count;v171_result($category,$command,$code===0?'PASS':($critical?'FAIL':'WARNING'),$detail.($pass_count?', nested_assertions='.$pass_count:'').($code?'; '.implode(' | ',array_slice($lines,-3)):''));return $code===0;}
function v171_json_manifest($path,$artifact,$top){$data=json_decode(file_get_contents($path),true);return is_array($data)&&($data['version']??'')==='17.1.0'&&($data['artifact_filename']??'')===basename($artifact)&&($data['top_level_folder']??'')===$top&&($data['byte_size']??-1)===filesize($artifact)&&($data['sha256']??'')===hash_file('sha256',$artifact);}

$plugin=v171_read('plugins/region9-live-studio/region9-live-studio.php');$generator=v171_read('plugins/region9-live-studio/includes/class-product-generator.php');$scheduler=v171_read('plugins/region9-live-studio/includes/class-scheduler.php');$guidance=v171_read('plugins/region9-live-studio/includes/class-national-guidance.php');$rest=v171_read('plugins/region9-live-studio/includes/class-rest-api.php');$admin=v171_read('plugins/region9-live-studio/includes/class-admin.php');$style=v171_read('style.css');$functions=v171_read('functions.php');$home=v171_read('template-parts-studio-home.php');$sidebar=v171_read('sidebar.php');$integration=v171_read('inc/live-studio-integration.php');
v171_check('ENVIRONMENT','PHP compatibility',version_compare(PHP_VERSION,'7.4','>='),PHP_VERSION);foreach(array('json','date','hash') as $extension)v171_check('ENVIRONMENT','PHP extension '.$extension,extension_loaded($extension));v171_check('ENVIRONMENT','WordPress compatibility assumptions',strpos($plugin,'Plugin Name: Region 9 Live Studio')!==false&&strpos($functions,'add_action')!==false,'WordPress >=6.0 package metadata');
v171_check('VERSION','Plugin header and runtime are 17.1.0',strpos($plugin,'Version: 17.1.0')!==false&&strpos($plugin,"R9LS_VERSION', '17.1.0")!==false);v171_check('VERSION','Schema and migration are 17.1.0',strpos($generator,"const VERSION = '17.1.0'")!==false&&strpos($generator,"upgraded_from'=>'17.0.0-rc.1'")!==false);v171_check('VERSION','Theme metadata and cache versions are 17.1.0',preg_match('/^Version:\s*17\.1\.0$/mi',$style)&&strpos($functions,"R9_STUDIO_VERSION','17.1.0")!==false&&strpos($functions,"R9WS_VERSION','17.1.0")!==false&&strpos($functions,"R9WS_THEME_VERSION','17.1.0")!==false);v171_check('VERSION','REST metadata exposes 17.1.0',strpos($rest,"'metadata'=>'metadata'")!==false&&strpos($rest,"'version'=>R9LS_VERSION")!==false);v171_check('VERSION','GeneratePress relationship preserved',preg_match('/^Template:\s*generatepress$/mi',$style));
v171_check('INSTALL_UPGRADE','Migration runs on boot and activation',substr_count($plugin,'migrate_17_1')>=2);foreach(array('r9ls_published_products','r9ls_forecast_production_workspace','r9ls_decision_history','r9ls_publication_history','r9ls_product_history','r9ls_pending_changes','r9ls_editor_overrides','r9ls_live_controls','r9ls_settings','r9ls_source_health','r9ls_canonical_alert_state') as $option)v171_check('INSTALL_UPGRADE','Migration preservation '.$option,strpos($generator,$option)!==false);v171_check('INSTALL_UPGRADE','Migration idempotency marker',strpos($generator,"status'] ?? '') === 'complete'")!==false);
v171_check('SCHEDULER','Recurring and self-healing scheduler',strpos($scheduler,'wp_schedule_event')!==false&&strpos($scheduler,'next_validation()')!==false);v171_check('SCHEDULER','Overlap and stale-lock protection',strpos($scheduler,'self::LOCK')!==false&&strpos($scheduler,'Expired validation lock')!==false);v171_check('SCHEDULER','Manual and scheduled validation paths',strpos($scheduler,"validate('manual')")!==false&&strpos($scheduler,"validate('scheduled')")!==false);
foreach(array('nws_alerts','nws_points_grid_hourly','spc_day1','wpc_day1_ero','wpc_day1_qpf','stale_cached_result','unavailable_source','malformed','timeout') as $needle)v171_check('SOURCES','Source capability '.$needle,strpos($guidance.$scheduler,$needle)!==false);v171_check('SOURCES','No false all-clear',strpos($guidance,'healthy_zero_alerts')!==false);v171_check('SOURCES','Missing source reduces confidence without adding risk',strpos(v171_read('plugins/region9-live-studio/includes/class-rule-engine.php'),'confidence -=')!==false);
foreach(array('r9ls_canonical_alert_state','healthy_zero_alerts','Polygon','MultiPolygon','affected_counties','description','instruction','ends') as $needle)v171_check('ALERT_CENTER','Alert capability '.$needle,strpos($guidance.$rest.$admin,$needle)!==false);v171_check('ALERT_CENTER','Public alert filtering',strpos($rest,'array_intersect_key')!==false);v171_check('ALERT_CENTER','Homepage/admin canonical consistency',strpos($functions,'r9ls_get_canonical_alert_state')!==false&&strpos($admin,"r9ls_canonical_alert_state")!==false);
$geo=json_decode(v171_read('plugins/region9-live-studio/data/region9-counties.geojson'),true);v171_check('GIS','Exactly nine county geometries',count((array)($geo['features']??array()))===9);$geoids=array();$closed=true;foreach((array)($geo['features']??array()) as $feature){$geoids[]=$feature['properties']['GEOID']??'';$geometry=$feature['geometry']??array();$rings=($geometry['type']??'')==='Polygon'?($geometry['coordinates']??array()):array_merge(...($geometry['coordinates']??array()));foreach($rings as $ring){if(!$ring||reset($ring)!==end($ring))$closed=false;}}sort($geoids);$expected=array('17019','17039','17053','17075','17091','17105','17113','17147','17183');sort($expected);v171_check('GIS','Valid Region 9 GEOIDs',$geoids===$expected);v171_check('GIS','Geometry rings close',$closed);v171_check('GIS','Polygon and MultiPolygon support',strpos(v171_read('plugins/region9-live-studio/includes/class-gis-engine.php'),'MultiPolygon')!==false);
foreach(array('morning-brief','todays-forecast','seven-day-forecast','headlines','travel','agriculture','forecast-confidence') as $product)v171_check('PRODUCTION','Canonical product '.$product,strpos($generator,"'$product'")!==false);foreach(array('refresh_workspace_from_decision','grouped_changes','unchanged_available_for_review','changed_pending_review','content_hash','generation_duration','append_decision_history','approve(','reject(','publish(','rollback(','duplicate_publication','publication_failed') as $needle)v171_check('PRODUCTION','Pipeline capability '.$needle,strpos($generator,$needle)!==false);v171_check('PRODUCTION','Public drafts excluded',strpos($rest,"approval_state'] ?? '') === 'approved'")!==false&&strpos($rest,"publication_state'] ?? '') === 'published'")!==false);
foreach(array('r9-home-radar-hero','Decision Impact Dashboard','Current Conditions','r9_home_forecast_module','r9-home-sidebar','r9_home_outage_module') as $needle)v171_check('HOMEPAGE','Homepage component '.$needle,strpos($home.$functions,$needle)!==false);v171_check('HOMEPAGE','Responsive stacking and overflow protection',strpos($home,'r9-mobile-stack-home')!==false&&strpos($style,'overflow')!==false);v171_check('HOMEPAGE','No render-time source ingestion',strpos($home,'wp_remote_get')===false&&strpos($sidebar,'wp_remote_get')===false);
v171_check('ADMIN','One plugin top-level menu',substr_count($admin,"add_menu_page('Region 9 Studio Automation'")===1);foreach(array('forecast_production_page','forecast_products_page','approval_queue_page','decision_dashboard_page','decision_history_page','publication_history_page','alert_center_page','source_health_page','scheduler_health_page','automation_page','theme_setup_page','theme_health_page','backup_page','live_controls_page','partners_page','clients_page','production_page','rural_operations_page','rural_reports_page','protection_page') as $callback)v171_check('ADMIN','Dedicated callback '.$callback,strpos($admin,'function '.$callback.'(')!==false);v171_check('ADMIN','Capabilities/nonces/sanitization/escaping',strpos($admin,"current_user_can('manage_options')")!==false&&strpos($admin,'check_admin_referer')!==false&&strpos($admin,'sanitize_key')!==false&&strpos($admin,'esc_html')!==false);
v171_check('PUBLIC_SAFETY','No public write routes',strpos($rest,"'methods'=>'POST'")===false&&strpos($rest,'CREATABLE')===false);v171_check('PUBLIC_SAFETY','No internal trace exposure',strpos($rest,"unset(\$clean['rule_trace']")!==false);v171_check('PUBLIC_SAFETY','No MutationObserver scanning',strpos(v171_read('assets/js/studio.js'),'MutationObserver')===false&&strpos(v171_read('assets/js/v52.js'),'MutationObserver')===false);v171_check('PUBLIC_SAFETY','No raw payload in admin renderer',strpos($admin,"['payload']")===false);
v171_check('ACCESSIBILITY','Fallback image text',strpos($functions,'role="img"')!==false||strpos($functions,'r9_media_placeholder')!==false);v171_check('ACCESSIBILITY','Status not color alone',strpos($admin,'r9ls-health-badge')!==false);v171_check('ACCESSIBILITY','Keyboard-safe native controls',strpos($admin,'<button')!==false&&strpos($admin,'<details>')!==false);v171_check('ACCESSIBILITY','Reduced motion support',strpos($style,'prefers-reduced-motion')!==false);v171_check('ACCESSIBILITY','Responsive admin tables',strpos($admin,'overflow-x:auto')!==false);
$plugin_builder=v171_read('scripts/build-region9-live-studio-zip.sh');v171_check('PACKAGING','Plugin builder metadata',strpos($plugin_builder,'VERSION="17.1.0"')!==false&&strpos($plugin_builder,'"artifact_filename"')!==false&&strpos($plugin_builder,'"byte_size"')!==false&&strpos($plugin_builder,'"sha256"')!==false);v171_check('PACKAGING','Theme builder metadata',strpos(v171_read('scripts/build-region9-weather-theme-zip.sh'),'VERSION="17.1.0"')!==false);v171_check('PACKAGING','Theme folder is current stylesheet directory',strpos(v171_read('scripts/build-region9-weather-theme-zip.sh'),'basename "$ROOT"')!==false);$existing_plugin_zip=$build.'/region9-live-studio-17.1.0.zip';$existing_plugin_manifest=$build.'/region9-live-studio-17.1.0-manifest.json';if(is_file($existing_plugin_zip)&&is_file($existing_plugin_manifest))v171_check('PACKAGING','Existing plugin manifest field contract',v171_json_manifest($existing_plugin_manifest,$existing_plugin_zip,'region9-live-studio'));

$quick_commands=array('find plugins/region9-live-studio -name \'*.php\' -print0 | xargs -0 -n1 php -l','php scripts/validate-v17.1-homepage.php','php scripts/validate-v17.1-production-pipeline.php','php scripts/validate-v17.1-admin.php','php scripts/validate-theme-rc1-admin-integration.php','php scripts/validate-rc1-public-surface.php','php scripts/validate-v15-parity.php');foreach($quick_commands as $command)v171_run('VALIDATION',$command);
if($mode!=='quick'){foreach(array('php scripts/validate-region9-live-studio.php','php scripts/rc1-validation-suite.php') as $command)v171_run('FULL_VALIDATION',$command);v171_run('PERFORMANCE','php scripts/rc1-scheduler-soak.php 6 2');}
if($mode==='stress'){$cycles=max(3,(int)(getenv('R9LS_STRESS_CYCLES')?:5));$memory=memory_get_usage(true);for($i=1;$i<=$cycles;$i++){v171_run('STRESS','php scripts/validate-v17.1-production-pipeline.php');v171_run('STRESS','php scripts/rc1-validation-suite.php');}v171_result('STRESS','Isolated repeated cycles','PASS',$cycles.' cycles; certification memory delta='.(memory_get_usage(true)-$memory).' bytes');}
if($mode!=='quick'){v171_run('PACKAGING','bash scripts/build-region9-live-studio-zip.sh');v171_run('PACKAGING','bash scripts/build-region9-weather-theme-zip.sh');$plugin_zip=$build.'/region9-live-studio-17.1.0.zip';$theme_zip=$build.'/region9-weather-theme-17.1.0.zip';v171_check('PACKAGING','Plugin ZIP integrity',is_file($plugin_zip)&&v171_run('PACKAGING','unzip -t build/'.basename($plugin_zip)));v171_check('PACKAGING','Theme ZIP integrity',is_file($theme_zip)&&v171_run('PACKAGING','unzip -t build/'.basename($theme_zip)));if(is_file($plugin_zip))v171_check('PACKAGING','Plugin manifest integrity',v171_json_manifest($build.'/region9-live-studio-17.1.0-manifest.json',$plugin_zip,'region9-live-studio'));if(is_file($theme_zip))v171_check('PACKAGING','Theme manifest integrity',v171_json_manifest($build.'/region9-weather-theme-17.1.0-manifest.json',$theme_zip,basename($root)));v171_run('PACKAGING','(cd build && sha256sum -c SHA256SUMS.txt)');}
v171_result('UPSTREAM','Reference v15/v15.1 ZIP availability','UPSTREAM UNAVAILABLE','Reference ZIPs were not present in this execution filesystem.');
$summary=array('component'=>'Region 9 Live Studio','version'=>'17.1.0','mode'=>$mode,'generated_at'=>date('c'),'duration_seconds'=>round(microtime(true)-$started,3),'status'=>$failures?'FAIL':'PASS','assertion_count'=>$assertions,'failures'=>$failures,'warnings'=>$warnings,'peak_memory_bytes'=>memory_get_peak_usage(true),'results'=>$results);file_put_contents($build.'/v17.1-final-certification.json',json_encode($summary,JSON_PRETTY_PRINT|JSON_UNESCAPED_SLASHES));
$txt="Region 9 Live Studio 17.1.0 Final Certification\nMode: $mode\nStatus: {$summary['status']}\nAssertions: $assertions\nFailures: $failures\nWarnings: $warnings\n";foreach($results as $result)$txt.="[{$result['status']}] [{$result['category']}] {$result['name']}".($result['detail']!==''?' — '.$result['detail']:'')."\n";file_put_contents($build.'/v17.1-final-certification.txt',$txt);
$md="# Region 9 Live Studio 17.1.0 Final Certification\n\n- Mode: `$mode`\n- Status: **{$summary['status']}**\n- Assertions: `$assertions`\n- Failures: `$failures`\n- Warnings: `$warnings`\n\n| Classification | Category | Check | Detail |\n|---|---|---|---|\n";foreach($results as $result)$md.='| '.$result['status'].' | '.str_replace('|','/',$result['category']).' | '.str_replace('|','/',$result['name']).' | '.str_replace(array("\n",'|'),array('<br>','/'),$result['detail'])." |\n";file_put_contents($build.'/v17.1-final-certification.md',$md);exit($failures?1:0);
