<?php
if (!defined('ABSPATH')) { define('ABSPATH', __DIR__); }
function absint($v){ return abs((int)$v); } function sanitize_key($v){ return preg_replace('/[^a-z0-9_\-]/','', strtolower((string)$v)); }
function sanitize_text_field($v){ return is_array($v) ? '' : trim(strip_tags((string)$v)); } function wp_json_encode($v,$o=0){ return json_encode($v,$o); }
function apply_filters($tag,$value){ return $value; } function current_time(){ return date('Y-m-d H:i:s'); }
$GLOBALS['wp_options']=array(); $GLOBALS['wp_transients']=array(); $GLOBALS['scheduled']=array(); $GLOBALS['http_queue']=array();
function get_option($k,$d=false){ return $GLOBALS['wp_options'][$k] ?? $d; } function update_option($k,$v,$a=false){ $GLOBALS['wp_options'][$k]=$v; return true; } function delete_transient($k){ unset($GLOBALS['wp_transients'][$k]); }
function set_transient($k,$v,$ttl){ $GLOBALS['wp_transients'][$k]=array($v,time()+$ttl); } function get_transient($k){ if(!isset($GLOBALS['wp_transients'][$k])) return false; if($GLOBALS['wp_transients'][$k][1] < time()){ unset($GLOBALS['wp_transients'][$k]); return false;} return $GLOBALS['wp_transients'][$k][0]; }
function wp_next_scheduled($h){ return $GLOBALS['scheduled'][$h] ?? false; } function wp_schedule_event($t,$r,$h){ if(isset($GLOBALS['scheduled'][$h])) return false; $GLOBALS['scheduled'][$h]=$t; return true; } function wp_clear_scheduled_hook($h){ unset($GLOBALS['scheduled'][$h]); } function wp_parse_args($a,$d){ return array_merge($d,$a); }
function wp_remote_get($url,$args=array()){ return array_shift($GLOBALS['http_queue']) ?: array('response'=>array('code'=>503),'body'=>''); } function wp_remote_retrieve_response_code($r){ return $r['response']['code'] ?? 0; } function wp_remote_retrieve_body($r){ return $r['body'] ?? ''; } function is_wp_error($r){ return false; }
define('MINUTE_IN_SECONDS',60); define('HOUR_IN_SECONDS',3600); define('R9LS_DIR', dirname(__DIR__) . '/plugins/region9-live-studio/');
require R9LS_DIR.'includes/class-audit-log.php'; require R9LS_DIR.'includes/class-gis-engine.php'; require R9LS_DIR.'includes/class-rule-engine.php'; require R9LS_DIR.'includes/class-national-guidance.php'; require R9LS_DIR.'includes/class-material-change-engine.php'; require R9LS_DIR.'includes/class-scheduler.php';
function assert_true($name,$condition){ if(!$condition){ fwrite(STDERR,"FAIL: $name\n"); exit(1);} echo "PASS: $name\n"; }
function fc($label,$geometry,$extra=array()){ return array('type'=>'FeatureCollection','properties'=>array('issue'=>date('c'),'valid_from'=>date('c',time()-60),'valid_to'=>date('c',time()+3600)), 'features'=>array(array('type'=>'Feature','properties'=>array_merge(array('LABEL'=>$label),$extra),'geometry'=>$geometry))); }
function poly($x1,$y1,$x2,$y2){ return array('type'=>'Polygon','coordinates'=>array(array(array($x1,$y1),array($x2,$y1),array($x2,$y2),array($x1,$y2),array($x1,$y1)))); }
function remote_json($json,$code=200){ $GLOBALS['http_queue'][]=array('response'=>array('code'=>$code),'body'=>json_encode($json)); }
$a=new R9LS_Audit_Log(); $g=new R9LS_GIS_Engine(R9LS_DIR.'data/region9-counties.geojson'); $r=new R9LS_Rule_Engine($g,$a); $m=new R9LS_Material_Change_Engine($a); $ng=new R9LS_National_Guidance($g,$a,array('cache_ttl'=>1,'stale_ttl'=>60)); $s=new R9LS_Scheduler($a,$r,$m,$ng);
$s->ensure_defaults(); assert_true('minimum interval', $s->active_interval_minutes()===60); $s->schedule_event(); $first=wp_next_scheduled(R9LS_Scheduler::HOOK); $s->schedule_event(); assert_true('scheduler duplicate prevention', $first===wp_next_scheduled(R9LS_Scheduler::HOOK));
set_transient(R9LS_Scheduler::LOCK, time()-2000, 1); assert_true('lock expiration', $s->locked()===false);
$boone=poly(-92.6,38.8,-92.0,39.3); $multi=array('type'=>'MultiPolygon','coordinates'=>array($boone['coordinates'], poly(-92.0,38.3,-91.4,38.9)['coordinates'])); $none=poly(-100,30,-99,31);
assert_true('SPC Polygon intersection', in_array('Boone',$g->intersect_source(array('status'=>'healthy','hazards'=>array(array('risk'=>3,'geometry'=>$boone))))['affected_counties'],true));
assert_true('SPC MultiPolygon intersection', count($g->intersect_source(array('status'=>'healthy','hazards'=>array(array('risk'=>4,'geometry'=>$multi))))['affected_counties'])>=2);
remote_json(fc('SLGT',$none)); $spc_none=$ng->spc_day1(); assert_true('valid SPC outlook with no Region 9 intersection', $spc_none['status']==='healthy' && $spc_none['highest_risk']===0);
remote_json(array('type'=>'FeatureCollection','properties'=>array('issue'=>'2000-01-01T00:00:00Z','valid_from'=>'2000-01-01T00:00:00Z','valid_to'=>'2000-01-02T00:00:00Z'),'features'=>array(array('type'=>'Feature','properties'=>array('LABEL'=>'SLGT'),'geometry'=>$boone)))); delete_transient('r9ls_guidance_spc_day1'); assert_true('stale SPC response', $ng->spc_day1()['status']==='stale');
remote_json(array('type'=>'FeatureCollection','features'=>array(array('type'=>'Feature','properties'=>array('LABEL'=>'SLGT'),'geometry'=>array('type'=>'LineString','coordinates'=>array()))))); delete_transient('r9ls_guidance_spc_day1'); assert_true('malformed SPC geometry', $ng->spc_day1()['source_health']==='malformed_geometry');
remote_json(fc('MRGL',$boone)); assert_true('WPC ERO Polygon', $ng->wpc_ero_day1()['highest_category']==='Marginal'); delete_transient('r9ls_guidance_wpc_day1_ero'); remote_json(fc('HIGH',$multi)); assert_true('WPC ERO MultiPolygon', $ng->wpc_ero_day1()['highest_category']==='High');
delete_transient('r9ls_guidance_wpc_day1_ero'); remote_json(fc('MRGL',$none)); $ero0=$ng->wpc_ero_day1(); assert_true('WPC zero-impact healthy response', $ero0['status']==='healthy' && empty($ero0['affected_counties'])); delete_transient('r9ls_guidance_wpc_day1_ero'); update_option('r9ls_guidance_wpc_day1_ero_stale', array(), false); $GLOBALS['http_queue']=array(array('response'=>array('code'=>503),'body'=>''),array('response'=>array('code'=>503),'body'=>''),array('response'=>array('code'=>503),'body'=>'')); assert_true('WPC unavailable response', $ng->wpc_ero_day1()['status']==='unavailable');
delete_transient('r9ls_guidance_wpc_day1_qpf'); remote_json(array('type'=>'FeatureCollection','features'=>array(array('type'=>'Feature','properties'=>array('qpf_mm'=>25.4),'geometry'=>$boone)))); $q=$ng->wpc_qpf_day1(); assert_true('QPF parsing and unit conversion', abs($q['county_precipitation']['Boone']-1.0)<0.01 && $q['unit']==='in');
delete_transient('r9ls_guidance_spc_day1'); update_option('r9ls_guidance_spc_day1_stale', array(), false); $GLOBALS['http_queue']=array(); remote_json(fc('SLGT',$boone)); $ng->spc_day1(); $hit=$ng->spc_day1(); assert_true('cache hit', $hit['cache']==='hit'); sleep(2); $GLOBALS['http_queue']=array(array('response'=>array('code'=>503),'body'=>''),array('response'=>array('code'=>503),'body'=>''),array('response'=>array('code'=>503),'body'=>'')); assert_true('cache expiration and stale fallback', $ng->spc_day1()['status']==='stale');
$health=get_option(R9LS_National_Guidance::HEALTH,array()); assert_true('source degradation and recovery logged health', isset($health['spc_day1']));
$healthy=array('spc_day1'=>array('status'=>'healthy','hazards'=>array()),'wpc_day1_ero'=>array('status'=>'healthy','hazards'=>array()),'wpc_day1_qpf'=>array('status'=>'healthy','county_precipitation'=>array()),'nws_alerts'=>array('status'=>'healthy','hazards'=>array())); assert_true('healthy source with zero hazards', $r->evaluate_all($healthy)['Travel']['confidence']===100);
$bad=$healthy; $bad['spc_day1']=array('status'=>'unavailable'); $bad['wpc_day1_qpf']=array('status'=>'unavailable'); assert_true('confidence reduction when national guidance is unavailable', $r->evaluate_all($bad)['Travel']['confidence']<100);
$prev=$r->evaluate_all($healthy); $cur=$prev; $cur['Travel']['score']=80; $cur['Travel']['rating']='Dangerous'; $changes=$m->detect($prev,$cur); assert_true('material-change detection', count($changes)>=2); assert_true('approval-before-publish requirement', $m->publish($changes[0]['id'])===false); $m->decide($changes[0]['id'],'approved'); assert_true('publish after approval', $m->publish($changes[0]['id'])===true); assert_true('rollback behavior', $m->rollback($changes[0]['id'])===true);
update_option('r9ls_editor_overrides',array('x'=>array('expires'=>'2000-01-01T00:00'))); assert_true('override expiration', $m->expire_overrides()===array());
echo "Region 9 Live Studio validation complete.\n";
