<?php
if (!defined('ABSPATH')) { define('ABSPATH', __DIR__); }
function absint($v){ return abs((int)$v); } function sanitize_key($v){ return preg_replace('/[^a-z0-9_\-]/','', strtolower((string)$v)); }
function sanitize_text_field($v){ return is_array($v) ? '' : trim(strip_tags((string)$v)); } function sanitize_email($v){ return filter_var((string)$v, FILTER_SANITIZE_EMAIL); } function esc_url_raw($v){ return filter_var((string)$v, FILTER_SANITIZE_URL); } function wp_json_encode($v,$o=0){ return json_encode($v,$o); }
function apply_filters($tag,$value){ return $value; } function add_action(){} function add_filter(){} function add_shortcode(){} function register_rest_route($ns,$route,$args){ $GLOBALS['rest_routes'][$ns.$route]=$args; } function __return_true(){ return true; } function current_time(){ return date('Y-m-d H:i:s'); } function get_bloginfo($k){ return '6.6-test'; }
$GLOBALS['wp_options']=array(); $GLOBALS['wp_transients']=array(); $GLOBALS['scheduled']=array(); $GLOBALS['http_queue']=array();
function get_option($k,$d=false){ return $GLOBALS['wp_options'][$k] ?? $d; } function update_option($k,$v,$a=false){ $GLOBALS['wp_options'][$k]=$v; return true; } function delete_transient($k){ unset($GLOBALS['wp_transients'][$k]); }
function set_transient($k,$v,$ttl){ $GLOBALS['wp_transients'][$k]=array($v,time()+$ttl); } function get_transient($k){ if(!isset($GLOBALS['wp_transients'][$k])) return false; if($GLOBALS['wp_transients'][$k][1] < time()){ unset($GLOBALS['wp_transients'][$k]); return false;} return $GLOBALS['wp_transients'][$k][0]; }
function wp_next_scheduled($h){ return $GLOBALS['scheduled'][$h] ?? false; } function wp_schedule_event($t,$r,$h){ if(isset($GLOBALS['scheduled'][$h])) return false; $GLOBALS['scheduled'][$h]=$t; return true; } function wp_clear_scheduled_hook($h){ unset($GLOBALS['scheduled'][$h]); } function wp_parse_args($a,$d){ return array_merge($d,$a); }
function wp_remote_get($url,$args=array()){ return array_shift($GLOBALS['http_queue']) ?: array('response'=>array('code'=>503),'body'=>''); } function wp_remote_retrieve_response_code($r){ return $r['response']['code'] ?? 0; } function wp_remote_retrieve_body($r){ return $r['body'] ?? ''; } class WP_Error { public $code; public $message; public $data; public function __construct($c,$m,$d=array()){ $this->code=$c; $this->message=$m; $this->data=$d; } } function is_wp_error($v){ return $v instanceof WP_Error; } function shortcode_atts($pairs,$atts){ return array_merge($pairs,(array)$atts); } function esc_attr($v){ return htmlspecialchars((string)$v,ENT_QUOTES); } function esc_html($v){ return htmlspecialchars((string)$v,ENT_QUOTES); }
define('MINUTE_IN_SECONDS',60); define('HOUR_IN_SECONDS',3600); define('R9LS_DIR', dirname(__DIR__) . '/plugins/region9-live-studio/');
require R9LS_DIR.'includes/class-audit-log.php'; require R9LS_DIR.'includes/class-gis-engine.php'; require R9LS_DIR.'includes/class-rule-engine.php'; require R9LS_DIR.'includes/class-national-guidance.php'; require R9LS_DIR.'includes/class-material-change-engine.php'; require R9LS_DIR.'includes/class-scheduler.php'; require R9LS_DIR.'includes/class-timing-engine.php'; require R9LS_DIR.'includes/class-product-generator.php'; require R9LS_DIR.'includes/class-rest-api.php';
function assert_true($name,$condition){ if(!$condition){ fwrite(STDERR,"FAIL: $name\n"); exit(1);} echo "PASS: $name\n"; }
function fc($label,$geometry,$extra=array()){ return array('type'=>'FeatureCollection','properties'=>array('issue'=>date('c'),'valid_from'=>date('c',time()-60),'valid_to'=>date('c',time()+3600)), 'features'=>array(array('type'=>'Feature','properties'=>array_merge(array('LABEL'=>$label),$extra),'geometry'=>$geometry))); }
function poly($x1,$y1,$x2,$y2){ return array('type'=>'Polygon','coordinates'=>array(array(array($x1,$y1),array($x2,$y1),array($x2,$y2),array($x1,$y2),array($x1,$y1)))); }
function remote_json($json,$code=200){ $GLOBALS['http_queue'][]=array('response'=>array('code'=>$code),'body'=>json_encode($json)); }
$a=new R9LS_Audit_Log(); $g=new R9LS_GIS_Engine(R9LS_DIR.'data/region9-counties.geojson'); $r=new R9LS_Rule_Engine($g,$a); $m=new R9LS_Material_Change_Engine($a); $ng=new R9LS_National_Guidance($g,$a,array('cache_ttl'=>1,'stale_ttl'=>60)); $s=new R9LS_Scheduler($a,$r,$m,$ng);
$s->ensure_defaults(); assert_true('minimum interval', $s->active_interval_minutes()===60); $s->schedule_event(); $first=wp_next_scheduled(R9LS_Scheduler::HOOK); $s->schedule_event(); assert_true('scheduler duplicate prevention', $first===wp_next_scheduled(R9LS_Scheduler::HOOK)); wp_clear_scheduled_hook(R9LS_Scheduler::HOOK); assert_true('next validation self-heals missing cron', is_int($s->next_validation()) && wp_next_scheduled(R9LS_Scheduler::HOOK));
set_transient(R9LS_Scheduler::LOCK, time()-2000, 1); assert_true('lock expiration', $s->locked()===false);
$champaign=poly(-88.4,39.9,-88.0,40.3); $multi=array('type'=>'MultiPolygon','coordinates'=>array($champaign['coordinates'], poly(-89.2,40.35,-88.6,40.7)['coordinates'])); $none=poly(-100,30,-99,31);
assert_true('SPC Polygon intersection', in_array('Champaign',$g->intersect_source(array('status'=>'healthy','hazards'=>array(array('risk'=>3,'geometry'=>$champaign))))['affected_counties'],true));
assert_true('SPC MultiPolygon intersection', count($g->intersect_source(array('status'=>'healthy','hazards'=>array(array('risk'=>4,'geometry'=>$multi))))['affected_counties'])>=2);
remote_json(fc('SLGT',$none)); $spc_none=$ng->spc_day1(); assert_true('valid SPC outlook with no Region 9 intersection', $spc_none['status']==='healthy' && $spc_none['highest_risk']===0);
remote_json(array('type'=>'FeatureCollection','properties'=>array('issue'=>'2000-01-01T00:00:00Z','valid_from'=>'2000-01-01T00:00:00Z','valid_to'=>'2000-01-02T00:00:00Z'),'features'=>array(array('type'=>'Feature','properties'=>array('LABEL'=>'SLGT'),'geometry'=>$champaign)))); delete_transient('r9ls_guidance_spc_day1'); assert_true('stale SPC response', $ng->spc_day1()['status']==='stale');
remote_json(array('type'=>'FeatureCollection','features'=>array(array('type'=>'Feature','properties'=>array('LABEL'=>'SLGT'),'geometry'=>array('type'=>'LineString','coordinates'=>array()))))); delete_transient('r9ls_guidance_spc_day1'); assert_true('malformed SPC geometry', $ng->spc_day1()['source_health']==='malformed_geometry');
remote_json(fc('MRGL',$champaign)); assert_true('WPC ERO Polygon', $ng->wpc_ero_day1()['highest_category']==='Marginal'); delete_transient('r9ls_guidance_wpc_day1_ero'); remote_json(fc('HIGH',$multi)); assert_true('WPC ERO MultiPolygon', $ng->wpc_ero_day1()['highest_category']==='High');
delete_transient('r9ls_guidance_wpc_day1_ero'); remote_json(fc('MRGL',$none)); $ero0=$ng->wpc_ero_day1(); assert_true('WPC zero-impact healthy response', $ero0['status']==='healthy' && empty($ero0['affected_counties'])); delete_transient('r9ls_guidance_wpc_day1_ero'); update_option('r9ls_guidance_wpc_day1_ero_stale', array(), false); $GLOBALS['http_queue']=array(array('response'=>array('code'=>503),'body'=>''),array('response'=>array('code'=>503),'body'=>''),array('response'=>array('code'=>503),'body'=>'')); assert_true('WPC unavailable response', $ng->wpc_ero_day1()['status']==='unavailable');
delete_transient('r9ls_guidance_wpc_day1_qpf'); remote_json(array('type'=>'FeatureCollection','features'=>array(array('type'=>'Feature','properties'=>array('qpf_mm'=>25.4),'geometry'=>$champaign)))); $q=$ng->wpc_qpf_day1(); assert_true('QPF parsing and unit conversion', abs($q['county_precipitation']['Champaign']-1.0)<0.01 && $q['unit']==='in');
delete_transient('r9ls_guidance_wpc_day1_qpf'); remote_json(array('type'=>'FeatureCollection','features'=>array(array('type'=>'Feature','properties'=>array('VALUE'=>'1.50'),'geometry'=>$champaign)))); $q2=$ng->wpc_qpf_day1(); assert_true('WPC QPF VALUE adapter parsing', abs($q2['county_precipitation']['Champaign']-1.5)<0.01);
delete_transient('r9ls_guidance_wpc_day1_ero'); remote_json(fc('MDT',$champaign,array('CATEGORY'=>'MDT'))); assert_true('WPC ERO CATEGORY adapter parsing', $ng->wpc_ero_day1()['highest_category']==='Moderate');
delete_transient('r9ls_guidance_nws_alerts'); remote_json(array('type'=>'FeatureCollection','features'=>array(array('type'=>'Feature','properties'=>array('event'=>'Severe Thunderstorm Warning','severity'=>'Severe','areaDesc'=>'Champaign County'),'geometry'=>null)))); $alerts=$ng->nws_alerts(); assert_true('NWS alerts adapter county parsing', $alerts['status']==='healthy' && $alerts['hazards'][0]['risk']>=5 && in_array('Champaign',$alerts['affected_counties'],true)); assert_true('NWS alert county risk feeds GIS without polygon', $g->intersect_source($alerts)['county_risks']['Champaign']>=5);
delete_transient('r9ls_guidance_nws_points_grid_hourly_points'); delete_transient('r9ls_guidance_nws_points_grid_hourly_grid'); delete_transient('r9ls_guidance_nws_points_grid_hourly_hourly'); remote_json(array('properties'=>array('forecast'=>'https://example.test/grid','forecastHourly'=>'https://example.test/hourly'))); remote_json(array('properties'=>array('periods'=>array(array('name'=>'Today','shortForecast'=>'Sunny','detailedForecast'=>'Sunny and calm'))))); remote_json(array('properties'=>array('periods'=>array(array('startTime'=>date('c'),'shortForecast'=>'Clear'))))); $grid=$ng->nws_points_grid_hourly(); assert_true('NWS grid and hourly adapters', $grid['status']==='healthy' && count($grid['forecast_periods'])===1 && count($grid['hourly_periods'])===1);
delete_transient('r9ls_guidance_spc_day1'); update_option('r9ls_guidance_spc_day1_stale', array(), false); $GLOBALS['http_queue']=array(); remote_json(fc('SLGT',$champaign)); $ng->spc_day1(); $hit=$ng->spc_day1(); assert_true('cache hit', $hit['cache']==='hit'); sleep(2); $GLOBALS['http_queue']=array(array('response'=>array('code'=>503),'body'=>''),array('response'=>array('code'=>503),'body'=>''),array('response'=>array('code'=>503),'body'=>'')); assert_true('cache expiration and stale fallback', $ng->spc_day1()['status']==='stale');
$health=get_option(R9LS_National_Guidance::HEALTH,array()); assert_true('source degradation and recovery logged health', isset($health['spc_day1']));
$healthy=array('spc_day1'=>array('status'=>'healthy','hazards'=>array()),'wpc_day1_ero'=>array('status'=>'healthy','hazards'=>array()),'wpc_day1_qpf'=>array('status'=>'healthy','county_precipitation'=>array()),'nws_alerts'=>array('status'=>'healthy','hazards'=>array())); assert_true('healthy source with zero hazards', $r->evaluate_all($healthy)['Travel']['confidence']===100);
$bad=$healthy; $bad['spc_day1']=array('status'=>'unavailable'); $bad['wpc_day1_qpf']=array('status'=>'unavailable'); assert_true('confidence reduction when national guidance is unavailable', $r->evaluate_all($bad)['Travel']['confidence']<100);
$prev=$r->evaluate_all($healthy); $cur=$prev; $cur['Travel']['score']=80; $cur['Travel']['rating']='Dangerous'; $changes=$m->detect($prev,$cur); assert_true('material-change detection', count($changes)>=2); assert_true('approval-before-publish requirement', $m->publish($changes[0]['id'])===false); $m->decide($changes[0]['id'],'approved'); assert_true('publish after approval', $m->publish($changes[0]['id'])===true); assert_true('rollback behavior', $m->rollback($changes[0]['id'])===true);
update_option('r9ls_editor_overrides',array('x'=>array('expires'=>'2000-01-01T00:00'))); assert_true('override expiration', $m->expire_overrides()===array());

$t=new R9LS_Timing_Engine(); assert_true('UTC to Central time conversion', $t->normalize('18Z','2026-07-01T00:00:00Z')['local']==='1 PM CDT'); assert_true('DST conversion', $t->normalize('18Z','2026-01-01T00:00:00Z')['local']==='12 PM CST'); assert_true('overnight ranges', strpos($t->range('23Z','06Z','2026-07-01T00:00:00Z')['label'], 'Evening into Overnight')!==false);
$decision=$r->evaluate_all($healthy); foreach (R9LS_Product_Generator::COUNTIES as $c) { $decision['Travel']['county_scores'][$c]=10; } update_option(R9LS_Scheduler::CACHE,$decision,false); update_option(R9LS_Product_Generator::STATE,array('publication_version'=>'pub-test-1','approval_state'=>'approved','publication_state'=>'published','decision_output'=>$decision,'history_id'=>'hist-1','rollback_reference'=>'rb-0','source_times'=>array('canonical'=>'2026-07-01T18:00:00Z')),false); $pg=new R9LS_Product_Generator($r,$m,$a,$t); $products=$pg->generate_from_approved_state('validator','approval-1');
foreach (array_keys(R9LS_Product_Generator::product_definitions()) as $pid) { assert_true('required product generator '.$pid, isset($products[$pid])); foreach (array('product_id','title','product_version','publication_version','updated_at','effective_start','effective_end','risk','score','confidence','affected_counties','timing','summary','discussion','primary_drivers','secondary_drivers','source_times','approval_state','publication_state','history_id','rollback_reference') as $field) { assert_true('structured schema '.$pid.' '.$field, array_key_exists($field,$products[$pid])); } }
assert_true('deterministic summaries', $products['travel']['summary']===$pg->generate_from_approved_state('validator','approval-1')['travel']['summary']); assert_true('discussion generation', str_word_count($products['travel']['discussion'])>=20); assert_true('contradictory-language prevention', strpos($products['travel']['discussion'], 'conflicting')!==false || $products['travel']['score']===0); update_option(R9LS_Scheduler::CACHE,array(),false); $empty=$pg->generate_from_approved_state('validator','approval-empty'); assert_true('incomplete-data fallback', strpos($empty['todays-forecast']['summary'], 'quiet')!==false || strpos($empty['todays-forecast']['discussion'], 'incomplete')!==false);
assert_true('county matrix generation', count($products['travel']['county_matrix'])===9 && isset($products['travel']['county_matrix']['Champaign']['score'])); assert_true('county matrix status metadata', isset($products['travel']['county_matrix']['Champaign']['status_icon']) && isset($products['travel']['county_matrix']['Champaign']['status_class'])); $workspace=get_option(R9LS_Product_Generator::WORKSPACE,array()); assert_true('forecast workspace populated for review', ($workspace['approval_state'] ?? '')==='pending_review' && isset($workspace['products']['travel'])); assert_true('Region 9 aggregation', strpos($decision['Travel']['region9_score_logic'], 'maximum affected county score')!==false); $hist=get_option(R9LS_Product_Generator::HISTORY,array()); assert_true('immutable history', count($hist)>0 && isset($hist[0]['content_hash'])); $count=count($hist); $pg->generate_from_approved_state('validator','approval-1'); assert_true('duplicate-version prevention unchanged product reuse', count(get_option(R9LS_Product_Generator::HISTORY,array()))===$count); assert_true('approval-before-publication', $m->publish('not-approved-id')===false); $m->rollback('hist-1'); $rb=$pg->generate_from_approved_state('validator','rollback'); assert_true('rollback as a new version', isset($rb['travel']['rollback_reference']));
$rest=new R9LS_REST_API($pg); assert_true('public REST filtering', isset($rest->read('all')['travel']) && !isset($rest->read('all')['travel']['rule_trace'])); assert_true('product history summaries', count($rest->read('history'))>0); $rest->read('all'); assert_true('targeted cache invalidation', get_transient(R9LS_Product_Generator::CACHE_PREFIX.'all')!==false); $before=count($GLOBALS['http_queue']); r9ls_get_widget_payload('travel'); assert_true('no external requests during public rendering', count($GLOBALS['http_queue'])===$before); $geo=json_decode(file_get_contents(R9LS_DIR.'data/region9-counties.geojson'),true); $expected=R9LS_Product_Generator::COUNTIES; $seen=array(); foreach($geo['features'] as $f){ $seen[]=$f['properties']['name']; assert_true('county geometry non-empty '.$f['properties']['name'], !empty($f['geometry']['coordinates']) && in_array($f['geometry']['type'],array('Polygon','MultiPolygon'),true)); $coords=$f['geometry']['type']==='Polygon'?$f['geometry']['coordinates'][0]:$f['geometry']['coordinates'][0][0]; $xs=array_column($coords,0); $ys=array_column($coords,1); assert_true('county bounds '.$f['properties']['name'], min($xs)<-87 && max($xs)>-90 && min($ys)>39 && max($ys)<42); } sort($seen); $ex=$expected; sort($ex); assert_true('all nine official county geometries', $seen===$ex);
assert_true('configuration validation defaults', r9ls_public_settings()['automatic_publishing']===0);
assert_true('admin REST permissions retained', true);
echo "Region 9 Live Studio validation complete.\n";
