<?php
defined('ABSPATH') || exit;

class R9LS_Admin {
    private $scheduler; private $changes; private $audit;
    public function __construct($scheduler, $changes, $audit) { $this->scheduler = $scheduler; $this->changes = $changes; $this->audit = $audit; }
    public function hooks() {
        add_action('admin_menu', array($this, 'menu'));
        add_action('admin_post_r9ls_validate', array($this, 'validate'));
        add_action('admin_post_r9ls_settings', array($this, 'settings'));
        add_action('admin_post_r9ls_change', array($this, 'change_action'));
        add_action('admin_post_r9ls_override', array($this, 'override'));
    }
    public function menu() { add_menu_page('Region 9 Studio Automation', 'Region 9 Studio', 'manage_options', 'r9ls', array($this, 'page'), 'dashicons-cloud', 58); }
    public function page() {
        if (!current_user_can('manage_options')) { wp_die(esc_html__('Administrator access required.', 'r9ls')); }
        $products = get_option(R9LS_Scheduler::CACHE, array()); $health = $this->scheduler->health(); $last = get_option(R9LS_Scheduler::LAST, array()); $queue = $this->changes->queue(); $settings = get_option(R9LS_Scheduler::SETTINGS, array());
        echo '<div class="wrap"><h1>Region 9 Studio Automation</h1>';
        echo '<h2>Operational Status</h2><table class="widefat"><tbody>';
        $rows = array('NWS Alerts health' => $this->source_state('nws_alerts'), 'NWS Points/Grid/Hourly health' => $this->source_state('nws_points_grid_hourly'), 'SPC health' => $this->source_state('spc_day1'), 'WPC ERO health' => $this->source_state('wpc_day1_ero'), 'WPC QPF health' => $this->source_state('wpc_day1_qpf'), 'Scheduler status' => ($health['status'] ?? 'unknown') . ' — ' . ($health['message'] ?? ''), 'Current publication version' => $this->publication_version(), 'Pending changes' => count($queue), 'Active overrides' => count(get_option('r9ls_editor_overrides', array())), 'Cache age' => $this->cache_age(), 'Stale sources' => $this->stale_sources(), 'Recent errors' => $this->recent_errors(), 'PHP version' => PHP_VERSION, 'WordPress version' => get_bloginfo('version'), 'Plugin version' => R9LS_VERSION, 'Theme integration status' => function_exists('r9ls_theme_integration_status') ? r9ls_theme_integration_status()['status'] : 'Unavailable', 'Current Region 9 risk' => $this->current_risk($products), 'Forecast confidence' => $products['Forecast Confidence']['confidence'] ?? 'N/A', 'Last validation' => $last['time'] ?? 'Never', 'Next validation' => $this->scheduler->next_validation() ? date_i18n('Y-m-d H:i:s', $this->scheduler->next_validation()) : 'Not scheduled', 'Validation duration' => isset($last['duration']) ? $last['duration'] . 's' : 'N/A');
        foreach ($rows as $k => $v) { echo '<tr><th>' . esc_html($k) . '</th><td>' . esc_html((string) $v) . '</td></tr>'; }
        echo '</tbody></table>';
        echo '<form method="post" action="' . esc_url(admin_url('admin-post.php')) . '"><input type="hidden" name="action" value="r9ls_validate">'; wp_nonce_field('r9ls_validate'); submit_button('Run Manual Validation'); echo '</form>';
        echo '<h2>Operational Product Cards</h2><div class="r9ls-cards">';
        foreach ($products as $name => $product) { echo '<div class="card"><h3>' . esc_html($name) . '</h3><p>' . esc_html($product['controlled_summary']) . '</p><p>Rating: ' . esc_html($product['rating']) . '</p></div>'; }
        echo '</div><h2>County Score Matrix</h2><table class="widefat"><tbody>';
        foreach (($products['Travel']['county_scores'] ?? array()) as $county => $score) { echo '<tr><th>' . esc_html($county) . '</th><td>' . esc_html((string) $score) . '</td></tr>'; }
        echo '</tbody></table><h2>Pending Material Changes</h2><table class="widefat"><tbody>';
        foreach ($queue as $id => $change) { echo '<tr><td>' . esc_html($change['product'] . ' ' . $change['field'] . ': ' . $change['reason']) . '</td><td>' . $this->button($id, 'approve') . $this->button($id, 'reject') . $this->button($id, 'publish') . $this->button($id, 'rollback') . '</td></tr>'; }
        echo '</tbody></table><h2>Temporary Editor Overrides</h2><form method="post" action="' . esc_url(admin_url('admin-post.php')) . '"><input type="hidden" name="action" value="r9ls_override">'; wp_nonce_field('r9ls_override'); echo '<input name="summary" placeholder="Override summary"> <input type="datetime-local" name="expires">'; submit_button('Save Override'); echo '</form>';
        echo '<h2>Forecast Production Workspace</h2>'; $generated = get_option('r9ls_product_generation_last', array()); $published = get_option(R9LS_Product_Generator::PRODUCTS, array()); echo '<p>Generation duration: ' . esc_html((string) ($generated['duration'] ?? 'N/A')) . 's</p><table class="widefat"><thead><tr><th>Product</th><th>Version</th><th>Approval</th><th>Publication</th><th>Summary</th></tr></thead><tbody>'; foreach ($published as $product) { echo '<tr><td>' . esc_html($product['title']) . '</td><td>' . esc_html((string) $product['product_version']) . '</td><td>' . esc_html($product['approval_state']) . '</td><td>' . esc_html($product['publication_state']) . '</td><td>' . esc_html($product['summary']) . '</td></tr>'; } echo '</tbody></table><h2>Decision History</h2><pre>' . esc_html(wp_json_encode($this->changes->history(), JSON_PRETTY_PRINT)) . '</pre><h2>Audit Log</h2><pre>' . esc_html(wp_json_encode($this->audit->all(), JSON_PRETTY_PRINT)) . '</pre>';
        echo '<h2>Settings</h2><form method="post" action="' . esc_url(admin_url('admin-post.php')) . '"><input type="hidden" name="action" value="r9ls_settings">'; wp_nonce_field('r9ls_settings');
        foreach ($this->settings_fields() as $key => $field) { $value = $settings[$key] ?? $field['default']; printf('<label>%s <input name="%s" type="%s" value="%s"></label><br>', esc_html($field['label']), esc_attr($key), esc_attr($field['type']), esc_attr(is_array($value) ? implode(',', $value) : $value)); }
        printf('<label><input name="automatic_publishing" type="checkbox" value="1" %s> Enable automatic publication</label><br>', !empty($settings['automatic_publishing']) ? 'checked' : ''); submit_button('Save Settings'); echo '</form></div>';
    }
    private function button($id, $do) { return '<form style="display:inline" method="post" action="' . esc_url(admin_url('admin-post.php')) . '"><input type="hidden" name="action" value="r9ls_change"><input type="hidden" name="change_id" value="' . esc_attr($id) . '"><input type="hidden" name="do" value="' . esc_attr($do) . '">' . wp_nonce_field('r9ls_change', '_wpnonce', true, false) . '<button class="button">' . esc_html(ucfirst($do)) . '</button></form> '; }
    public function validate() { $this->guard('r9ls_validate'); $this->scheduler->manual_validate(); wp_safe_redirect(admin_url('admin.php?page=r9ls')); exit; }
    public function settings() { $this->guard('r9ls_settings'); $clean = array(); foreach ($this->settings_fields() as $key => $field) { $raw = wp_unslash($_POST[$key] ?? $field['default']); if ($field['type'] === 'number') { $clean[$key] = max((int)($field['min'] ?? 0), absint($raw)); } elseif (!empty($field['csv'])) { $clean[$key] = array_filter(array_map('sanitize_key', array_map('trim', explode(',', (string)$raw)))); } elseif ($key === 'nws_contact_email') { $clean[$key] = sanitize_email($raw); } else { $clean[$key] = sanitize_text_field($raw); } } $clean['automatic_publishing'] = !empty($_POST['automatic_publishing']) ? 1 : 0; update_option(R9LS_Scheduler::SETTINGS, $clean, false); wp_safe_redirect(admin_url('admin.php?page=r9ls')); exit; }
    public function change_action() { $this->guard('r9ls_change'); $id = sanitize_text_field(wp_unslash($_POST['change_id'] ?? '')); $do = sanitize_key($_POST['do'] ?? ''); if ($do === 'approve' || $do === 'reject') { $this->changes->decide($id, $do); } elseif ($do === 'publish') { $this->changes->publish($id); } elseif ($do === 'rollback') { $this->changes->rollback($id); } wp_safe_redirect(admin_url('admin.php?page=r9ls')); exit; }
    public function override() { $this->guard('r9ls_override'); $overrides = get_option('r9ls_editor_overrides', array()); $overrides[md5(time() . wp_rand())] = array('summary' => sanitize_text_field(wp_unslash($_POST['summary'] ?? '')), 'expires' => sanitize_text_field(wp_unslash($_POST['expires'] ?? ''))); update_option('r9ls_editor_overrides', $overrides, false); wp_safe_redirect(admin_url('admin.php?page=r9ls')); exit; }
    private function guard($nonce) { if (!current_user_can('manage_options')) { wp_die('Administrator capability required.'); } check_admin_referer($nonce); }
    private function current_risk($products) { return $products['Severe Weather Risk']['rating'] ?? 'None'; }
    private function source_state($key) { $h = get_option(R9LS_National_Guidance::HEALTH, array()); $s = $h[$key]['status'] ?? 'Unavailable'; return in_array($s, array('healthy','stale','degraded','unavailable'), true) ? ucfirst($s) : esc_html($s); }
    private function publication_version() { $p = get_option(R9LS_Product_Generator::PRODUCTS, array()); $first = reset($p); return $first['publication_version'] ?? 'None'; }
    private function cache_age() { $last = get_option('r9ls_product_generation_last', array()); return $last['generated_at'] ?? 'Never'; }
    private function stale_sources() { $h = get_option(R9LS_National_Guidance::HEALTH, array()); $bad = array(); foreach ($h as $k => $v) { if (($v['status'] ?? '') !== 'healthy') { $bad[] = $k; } } return $bad ? implode(', ', $bad) : 'None'; }
    private function recent_errors() { return wp_json_encode(array_slice((array)$this->audit->all(), 0, 5)); }
    private function settings_fields() { return array('nws_contact_email'=>array('label'=>'NWS contact email','type'=>'email','default'=>'weather@region9weather.com'),'normal_validation_interval_minutes'=>array('label'=>'Normal validation interval minutes','type'=>'number','default'=>180,'min'=>15),'active_interval_minutes'=>array('label'=>'Active-weather interval minutes','type'=>'number','default'=>60,'min'=>15),'source_timeout_seconds'=>array('label'=>'Source timeout seconds','type'=>'number','default'=>10,'min'=>1),'cache_duration_minutes'=>array('label'=>'Cache duration minutes','type'=>'number','default'=>5,'min'=>1),'stale_data_threshold_minutes'=>array('label'=>'Stale-data threshold minutes','type'=>'number','default'=>720,'min'=>30),'confidence_threshold'=>array('label'=>'Confidence threshold','type'=>'number','default'=>60,'min'=>0),'material_change_threshold'=>array('label'=>'Material-change threshold','type'=>'number','default'=>10,'min'=>1),'required_healthy_sources'=>array('label'=>'Required healthy sources CSV','type'=>'text','default'=>'nws_alerts,spc_day1,wpc_day1_ero,wpc_day1_qpf','csv'=>true),'enabled_products'=>array('label'=>'Enabled products CSV','type'=>'text','default'=>implode(',', array_keys(R9LS_Product_Generator::product_definitions())),'csv'=>true),'fallback_language'=>array('label'=>'Fallback language','type'=>'text','default'=>'Region 9 Live Studio publication is temporarily unavailable.'),'public_display_options'=>array('label'=>'Public display options CSV','type'=>'text','default'=>'show_scores,show_counties','csv'=>true),'stale_banner_behavior'=>array('label'=>'Stale-data banner behavior','type'=>'text','default'=>'label')); }
}

